name: Continuous Integration

on:
  push:
    branches-ignore:
      - dev-server
  pull_request:
    branches-ignore:
      - dev-server

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Install sudo
        run: |
          apt-get update || sudo apt-get update
          apt-get install -y sudo || sudo echo
      - name: Install nodejs
        run: sudo apt-get install -y nodejs
      - uses: actions/checkout@v2
      - name: local-fix
        run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" | sudo tee /etc/lsb-release
          fi
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python/pip
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install Frontend Dependencies
        run: cd frontend && npm ci
      - name: Install apt dependencies
        run: |
          sudo apt-get install -y postgresql libpqxx-dev screen xvfb git nodejs build-essential default-jre wget libdbus-glib-1-2 xclip
      - name: Install firefox
        run: |
          wget -c https://download-installer.cdn.mozilla.net/pub/firefox/releases/84.0.1/linux-x86_64/en-US/firefox-84.0.1.tar.bz2
          tar -xvf firefox-84.0.1.tar.bz2
          sudo ln -fs $(pwd)/firefox/firefox /usr/bin/firefox
      - name: Install Backend dependencies
        run: cd backend && pip install -r requirements.txt
      - name: Run all tests
        run: ./tests.sh
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: integration-test-video
          path: integration_test/*.avi
